services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn my_portfolio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: portfolio-db